version: '2'
services:
    boncmd3-app:
        image: boncmd3
        external_links:
            - boncmd3-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/boncmd3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    boncmd3-mysql:
        extends:
            file: mysql.yml
            service: boncmd3-mysql
